"""Gym day detail models: catalog, concrete day plans, in-gym set log.

Layered ON TOP of the recurring GymScheduleSlot / TrainingPlan surfaces
(app/models/gym.py, training.py): resolve_range still answers "what is the
template for this date"; gym_day_plans is the CONCRETE plan for one date —
normally generated by the adaptive advisor (source='ai') or written manually
(source='manual'). gym_set_logs power the in-gym "next exercise + rest
timer" surface (API and Connect IQ watch window).
"""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    BigInteger,
    Date,
    DateTime,
    ForeignKey,
    Index,
    SmallInteger,
    Text,
    Integer,
    Numeric,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class GymExercise(Base):
    """Catalog row (seeded by migration 0006, extended via API)."""

    __tablename__ = "gym_exercises"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    # legs | push | pull | core | full_body
    muscle_group: Mapped[str] = mapped_column(Text, nullable=False)
    movement_pattern: Mapped[str] = mapped_column(Text, nullable=False)
    # low | medium | high — high-impact plyometrics get swapped out when the
    # advisor must protect joints (soreness, pre-event taper).
    impact_level: Mapped[str] = mapped_column(
        Text, nullable=False, default="low", server_default="low"
    )
    equipment: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default="now()"
    )


class GymDayPlan(Base):
    __tablename__ = "gym_day_plans"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    date: Mapped[date] = mapped_column(Date, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    # ai | manual | template
    source: Mapped[str] = mapped_column(
        Text, nullable=False, default="manual", server_default="manual"
    )
    # draft -> confirmed -> done
    status: Mapped[str] = mapped_column(
        Text, nullable=False, default="draft", server_default="draft"
    )
    # human-readable summary of the advisor's adjustments (taper, soreness...)
    adjustment_note: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default="now()"
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default="now()"
    )


class GymDayExercise(Base):
    __tablename__ = "gym_day_exercises"
    __table_args__ = (
        Index("ix_gym_day_exercises_plan", "gym_day_plan_id", "position"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    gym_day_plan_id: Mapped[int] = mapped_column(
        ForeignKey("gym_day_plans.id", ondelete="CASCADE"), nullable=False
    )
    exercise_id: Mapped[int] = mapped_column(
        ForeignKey("gym_exercises.id"), nullable=False
    )
    position: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    sets: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    reps_min: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    reps_max: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)
    rest_seconds: Mapped[int] = mapped_column(
        Integer, nullable=False, default=90, server_default="90"
    )
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default="now()"
    )


class GymSetLog(Base):
    __tablename__ = "gym_set_logs"
    __table_args__ = (
        Index("ix_gym_set_logs_user_time", "user_id", "done_at"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    gym_day_exercise_id: Mapped[int] = mapped_column(
        ForeignKey("gym_day_exercises.id", ondelete="CASCADE"), nullable=False
    )
    set_number: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    reps_done: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    weight_kg: Mapped[Decimal | None] = mapped_column(Numeric, nullable=True)
    done_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default="now()"
    )
