import AlphaUsagePanel from "./AlphaUsagePanel";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { api } from "../../app/api";
import { useUi } from "../../app/stores/ui";
import { Badge, Button, Card, CardHeader, ErrorNote, Loading, PageHeader } from "../../components/kit";

type Page<T> = { items: T[]; total?: number };
type User = { id: number; name: string; email: string; role: string; ai_access_tier: string; share_segments?: boolean; disabled: boolean; active_sessions?: number; last_login_at: string | null; created_at: string };
type Session = { id: number; user_id: number; created_at: string; expires_at: string; absolute_expires_at?: string | null; active?: boolean; remember_me: boolean };
type Invite = { id: number; code?: string; used_by: number | null; expired?: boolean; expires_at: string };
type Feedback = { id: number; user_id: number; category: string; message: string; page_url: string | null; created_at: string; notification_status?: "delivered" | "retrying" | "pending" };
type Log = { timestamp: string; level: string; source: string; event: string };
type NotificationStatus = { configured: boolean; pending: number; failed: number };

function date(value?: string | null) { return value ? new Date(value).toLocaleString() : "—"; }
function rows<T>(value: Page<T> | T[] | undefined): T[] { return Array.isArray(value) ? value : value?.items ?? []; }
function metricValue(key: string, value: unknown): string {
  if (key === "utilization_percent" && typeof value === "number") return `${value.toFixed(1)}%`;
  if (key.endsWith("_bytes") && typeof value === "number") return `${(value / 1_073_741_824).toFixed(1)} GiB`;
  return typeof value === "object" && value !== null ? JSON.stringify(value) : String(value ?? "—");
}

export default function AdminPage() {
  const { t } = useTranslation();
  const me = useUi((s) => s.me);
  const qc = useQueryClient();
  const [offset, setOffset] = useState({ users: 0, sessions: 0, invites: 0, feedback: 0 });
  const limit = 20;
  const users = useQuery({ queryKey: ["admin", "users", offset.users], queryFn: () => api.get<Page<User> | User[]>(`/api/admin/users?limit=${limit}&offset=${offset.users}`), refetchInterval: 30_000 });
  const sessions = useQuery({ queryKey: ["admin", "sessions", offset.sessions], queryFn: () => api.get<Page<Session> | Session[]>(`/api/admin/sessions?limit=${limit}&offset=${offset.sessions}`), refetchInterval: 30_000 });
  const invites = useQuery({ queryKey: ["admin", "invites", offset.invites], queryFn: () => api.get<Page<Invite> | Invite[]>(`/api/admin/invites?limit=${limit}&offset=${offset.invites}`) });
  const feedback = useQuery({ queryKey: ["admin", "feedback", offset.feedback], queryFn: () => api.get<Page<Feedback> | Feedback[]>(`/api/admin/feedback?limit=${limit}&offset=${offset.feedback}`), refetchInterval: 30_000 });
  const system = useQuery({ queryKey: ["admin", "system"], queryFn: () => api.get<Record<string, unknown>>("/api/admin/system"), refetchInterval: 15_000 });
  const [level, setLevel] = useState("");
  const [source, setSource] = useState("");
  const logs = useQuery({ queryKey: ["admin", "logs", level, source], queryFn: () => api.get<Page<Log> | Log[]>(`/api/admin/logs?limit=100${level ? `&level=${encodeURIComponent(level)}` : ""}${source ? `&source=${encodeURIComponent(source)}` : ""}`), refetchInterval: 20_000 });
  const notifications = useQuery({ queryKey: ["admin", "notifications"], queryFn: () => api.get<NotificationStatus>("/api/admin/notifications"), refetchInterval: 30_000 });
  const revokeUser = useMutation({ mutationFn: (u: User) => api.patch(`/api/admin/users/${u.id}`, { disabled: !u.disabled }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["admin", "users"] }); void qc.invalidateQueries({ queryKey: ["admin", "sessions"] }); } });
  const updatePermission = useMutation({ mutationFn: ({ id, values }: { id: number; values: Record<string, unknown> }) => api.patch(`/api/admin/users/${id}`, values), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin", "users"] }) });
  const revokeSessions = useMutation({ mutationFn: (id: number) => api.delete(`/api/admin/users/${id}/sessions`), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin", "sessions"] }) });
  const revokeSession = useMutation({ mutationFn: (id: number) => api.delete(`/api/admin/sessions/${id}`), onSuccess: () => { void qc.invalidateQueries({ queryKey: ["admin", "sessions"] }); void qc.invalidateQueries({ queryKey: ["admin", "users"] }); } });
  const mintInvite = useMutation({ mutationFn: () => api.post<Invite>("/api/admin/invites", { expires_in_days: 7 }), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin", "invites"] }) });
  const revokeInvite = useMutation({ mutationFn: (id: number) => api.delete(`/api/admin/invites/${id}`), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin", "invites"] }) });
  const testTelegram = useMutation({ mutationFn: () => api.post("/api/admin/notifications/test"), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin", "notifications"] }) });
  const all = [users, sessions, invites, feedback, system, logs, notifications];
  const error = all.find((q) => q.isError)?.error;
  const mutationError = [revokeUser, updatePermission, revokeSessions, revokeSession, mintInvite, revokeInvite].find((m) => m.isError)?.error;
  const urows = rows(users.data), srows = rows(sessions.data), irows = rows(invites.data), frows = rows(feedback.data), lrows = rows(logs.data);
  const systemData = system.data ?? {};
  const pager = (name: keyof typeof offset, data: Page<unknown> | unknown[] | undefined, count: number) => {
    const total = Array.isArray(data) ? data.length : data?.total ?? count;
    return total > limit ? <div className="flex items-center gap-2 text-xs text-muted"><span>{offset[name] + 1}–{Math.min(offset[name] + count, total)} / {total}</span><Button variant="ghost" className="!min-h-8 !px-2" disabled={offset[name] === 0} onClick={() => setOffset((o) => ({ ...o, [name]: Math.max(0, o[name] - limit) }))}>{t("admin.previous")}</Button><Button variant="ghost" className="!min-h-8 !px-2" disabled={offset[name] + limit >= total} onClick={() => setOffset((o) => ({ ...o, [name]: o[name] + limit }))}>{t("admin.next")}</Button></div> : null;
  };
  return <div className="space-y-7">
    <PageHeader title={t("admin.title")} subtitle={t("admin.subtitle")} />
    {error && <ErrorNote message={error instanceof Error ? error.message : t("admin.load_error")} />}
    {mutationError && <ErrorNote message={mutationError instanceof Error ? mutationError.message : t("admin.action_error")} />}
    <AlphaUsagePanel />
    <Card><CardHeader title={t("admin.system")} right={<span className="text-xs text-muted">{t("admin.refreshing")}</span>} />
      {system.isLoading ? <Loading /> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(systemData).flatMap(([key, value]) => {
        const fields = value && typeof value === "object" && !Array.isArray(value) ? Object.entries(value as Record<string, unknown>) : [[key, value] as [string, unknown]];
        if (Array.isArray(value)) return [[key, value.map((w) => { const worker = w as { name?: string; status?: string }; return `${worker.name ?? "worker"}: ${worker.status ?? "unknown"}`; }).join(", ") || t("admin.none")]] as [string, unknown][];
        return fields.map(([field, fieldValue]) => [field === "scope" ? `${key}_${field}` : field, fieldValue] as [string, unknown]);
      }).map(([key, value]) => <div key={key} className="border border-hairline p-3"><div className="text-xs uppercase text-muted">{t(`admin.metric_${key}`, { defaultValue: key.replaceAll("_", " ") })}</div><div className="mt-1 break-words text-lg font-medium">{metricValue(key, value)}</div></div>)}</div>}</Card>
    <Card><CardHeader title={t("admin.users")} right={pager("users", users.data, urows.length)} />{users.isLoading ? <Loading /> : <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead><tr className="border-b border-hairline text-muted"><th className="py-2">{t("admin.person")}</th><th>{t("admin.role")}</th><th>{t("admin.permissions")}</th><th>{t("admin.last_login")}</th><th>{t("admin.sessions_count")}</th><th>{t("admin.actions")}</th></tr></thead><tbody>{urows.map((u) => <tr key={u.id} className="border-b border-hairline"><td className="py-3"><div>{u.name}</div><div className="text-xs text-muted">{u.email}</div></td><td>{u.role === "owner" ? <Badge tone="primary">{t("admin.owner")}</Badge> : u.role}</td><td>{u.role === "owner" ? t("admin.owner_permissions") : u.disabled ? t("admin.revoked") : <div className="flex flex-col items-start gap-1"><select aria-label={t("admin.ai_access", { name: u.name })} value={u.ai_access_tier} disabled={updatePermission.isPending} onChange={(e) => updatePermission.mutate({ id: u.id, values: { ai_access_tier: e.target.value } })} className="border border-hairline bg-surface px-2 py-1"><option value="full">{t("admin.full_access")}</option><option value="cheap_only">{t("admin.limited_access")}</option></select>{u.share_segments !== undefined && <label className="flex items-center gap-1 text-xs text-muted"><input type="checkbox" checked={u.share_segments} disabled={updatePermission.isPending} onChange={(e) => updatePermission.mutate({ id: u.id, values: { share_segments: e.target.checked } })} />{t("admin.share_segments")}</label>}</div>}</td><td>{date(u.last_login_at)}</td><td>{u.active_sessions ?? 0}</td><td><div className="flex flex-wrap gap-2">{u.role !== "owner" && <><Button variant={u.disabled ? "ghost" : "danger"} className="!min-h-8 !px-2 text-xs" disabled={revokeUser.isPending} onClick={() => { if (window.confirm(t(u.disabled ? "admin.confirm_restore" : "admin.confirm_revoke", { name: u.name }))) revokeUser.mutate(u); }}>{t(u.disabled ? "admin.restore" : "admin.revoke")}</Button><Button variant="ghost" className="!min-h-8 !px-2 text-xs" onClick={() => { if (window.confirm(t("admin.confirm_sessions", { name: u.name }))) revokeSessions.mutate(u.id); }}>{t("admin.revoke_sessions")}</Button></>}</div></td></tr>)}</tbody></table></div>}</Card>
    <Card><CardHeader title={t("admin.sessions")} right={pager("sessions", sessions.data, srows.length)} />{sessions.isLoading ? <Loading /> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-hairline text-muted"><th className="py-2">{t("admin.user_id")}</th><th>{t("admin.created")}</th><th>{t("admin.expires")}</th><th>{t("admin.absolute_expires")}</th><th>{t("admin.session_status")}</th><th>{t("admin.remembered")}</th><th>{t("admin.actions")}</th></tr></thead><tbody>{srows.map((s) => { const isOwner = s.user_id === me?.user_id || urows.some((u) => u.id === s.user_id && u.role === "owner"); return <tr key={s.id} className="border-b border-hairline"><td className="py-3">{s.user_id}</td><td>{date(s.created_at)}</td><td>{date(s.expires_at)}</td><td>{date(s.absolute_expires_at)}</td><td>{t(s.active ? "admin.active" : "admin.inactive")}</td><td>{s.remember_me ? t("admin.yes") : t("admin.no")}</td><td>{!isOwner && <Button variant="danger" className="!min-h-8 !px-2 text-xs" disabled={revokeSession.isPending} onClick={() => { if (window.confirm(t("admin.confirm_session", { id: s.id }))) revokeSession.mutate(s.id); }}>{t("admin.revoke_session")}</Button>}</td></tr>; })}</tbody></table></div>}</Card>
    <Card><CardHeader title={t("admin.invites")} right={<div className="flex items-center gap-3">{pager("invites", invites.data, irows.length)}<Button disabled={mintInvite.isPending} onClick={() => mintInvite.mutate()}>{t("admin.create_invite")}</Button></div>} />{mintInvite.data?.code && <p role="status" className="mb-3 border border-hairline p-3">{t("admin.invite_code")}: <code>{mintInvite.data.code}</code></p>}{invites.isLoading ? <Loading /> : irows.map((i) => { const expired = i.expired ?? new Date(i.expires_at).getTime() <= Date.now(); return <div key={i.id} className="flex items-center justify-between border-b border-hairline py-2 text-sm"><span>#{i.id} · {date(i.expires_at)} · {i.used_by ? t("admin.used") : expired ? t("admin.expired") : t("admin.active")}</span>{!i.used_by && !expired && <Button variant="danger" className="!min-h-8 !px-2 text-xs" onClick={() => { if (window.confirm(t("admin.confirm_invite"))) revokeInvite.mutate(i.id); }}>{t("admin.revoke")}</Button>}</div>; })}</Card>
    <Card><CardHeader title={t("admin.telegram")} right={<Button variant="ghost" disabled={testTelegram.isPending || !notifications.data?.configured} onClick={() => testTelegram.mutate()}>{t("admin.test_telegram")}</Button>} />{notifications.isLoading ? <Loading /> : notifications.data && <div className="flex flex-wrap gap-4 text-sm"><span>{t("admin.configured")}: {notifications.data.configured ? t("admin.yes") : t("admin.no")}</span><span>{t("admin.pending")}: {notifications.data.pending}</span><span>{t("admin.failed")}: {notifications.data.failed}</span></div>}{testTelegram.isSuccess && <p role="status" className="mt-3 text-sm text-muted">{t("admin.test_queued")}</p>}{testTelegram.isError && <p role="alert" className="mt-3 text-sm text-alertText">{t("admin.test_failed")}</p>}</Card>
    <Card><CardHeader title={t("admin.feedback")} right={pager("feedback", feedback.data, frows.length)} />{feedback.isLoading ? <Loading /> : frows.length === 0 ? <p className="text-sm text-muted">{t("admin.no_feedback")}</p> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b border-hairline text-muted"><th className="py-2">{t("admin.category")}</th><th>{t("admin.user_id")}</th><th>{t("admin.message")}</th><th>{t("admin.page")}</th><th>{t("admin.created")}</th><th>{t("admin.delivery_status")}</th></tr></thead><tbody>{frows.map((f) => <tr key={f.id} className="border-b border-hairline align-top"><td className="py-3">{f.category}</td><td>{f.user_id}</td><td className="max-w-sm whitespace-pre-wrap">{f.message}</td><td>{f.page_url}</td><td>{date(f.created_at)}</td><td>{t(`admin.delivery_${f.notification_status ?? "pending"}`)}</td></tr>)}</tbody></table></div>}</Card>
    <Card><CardHeader title={t("admin.logs")} right={<div className="flex gap-2"><select aria-label={t("admin.filter_level")} value={level} onChange={(e) => setLevel(e.target.value)} className="border border-hairline bg-surface px-2 py-1 text-xs"><option value="">{t("admin.all_levels")}</option>{["debug", "info", "warning", "error", "critical"].map((v) => <option key={v} value={v.toUpperCase()}>{v}</option>)}</select><input aria-label={t("admin.filter_source")} value={source} onChange={(e) => setSource(e.target.value)} placeholder={t("admin.filter_source")} className="w-32 border border-hairline bg-surface px-2 py-1 text-xs" /></div>} />{logs.isLoading ? <Loading /> : <div className="max-h-96 overflow-auto">{lrows.map((l, n) => <div key={`${l.timestamp}-${n}`} className="grid gap-1 border-b border-hairline py-2 text-xs md:grid-cols-[160px_80px_120px_1fr]"><time className="text-muted">{date(l.timestamp)}</time><strong>{l.level}</strong><span>{l.source}</span><span className="break-words">{l.event}</span></div>)}</div>}</Card>
  </div>;
}
